### PR TITLE
Several small fixes to the docs

### PR DESCRIPTION
**Pull request by sloede**
The doc build worked, but apparently I missed a few things. I hope that fixes those.

cc @staticfloat @giordano

### CODE REVIEW

**Comment by sloede** [comment]
I switched to showing only the exported docstrings, since otherwise I think it is way too confusing for users. For this, I needed to set `warnonly = [:missing_docs]`, but I think it's ok, since we already include all exported docstrings.

Now it's ready for review from my POV.

**Comment by sloede** [comment]
Oh, and if this should get merged (I'm afk for a while), it would be great to tag a new patch release such that the stable docs link does not lead to nowhere.

**Comment by sloede** [comment]
Hm, something is amiss. No stable docs have been generated, but I don't understand why - the doc build ran successfully on the creation of the version tag: https://github.com/JuliaPackaging/Preferences.jl/actions/runs/6252363003/job/16975482523

@giordano would you know what's going on here?

**Comment by giordano** [comment]
I guess the problem is https://github.com/JuliaPackaging/Preferences.jl/blob/1282544ae890024d435ae925a23e13df0cbbc5de/.github/workflows/TagBot.yml#L15

**Comment by giordano** [comment]
https://juliapackaging.github.io/Preferences.jl/stable/

**Comment by sloede** [comment]
Great, thanks!

**Pull request merged**
