### PR TITLE
Precompile to reduce latency

### PR DESCRIPTION
**Pull request by timholy**
Motivated by https://github.com/JuliaLang/julia/pull/43990#issuecomment-1025692379,
but probably not a bad idea in its own right.

### CODE REVIEW

**Comment by giordano** [comment]
With Julia v1.7.1, on `master` (same as `v1.2.3`):
```julia
% julia --project=/tmp --startup-file=no -q
julia> @time using GTK3_jll
  0.104612 seconds (367.33 k allocations: 17.839 MiB, 24.74% compilation time)
```
(same as https://github.com/JuliaPackaging/JLLWrappers.jl/pull/38#pullrequestreview-868467189)

This PR:
```julia
% julia --project=/tmp --startup-file=no -q
julia> @time using GTK3_jll
  0.126395 seconds (415.97 k allocations: 22.106 MiB, 20.87% compilation time)
```

This seems to go in the wrong direction?

**Comment by timholy** [comment]
Hmm, I can confirm that. It seems like the final precompilation is bad news. Try the latest?

**Comment by timholy** [comment]
Checked, commenting out that last one doesn't eat into the benefits for https://github.com/JuliaLang/julia/pull/43990, if anything slightly improved.

**Comment by giordano** [comment]
Now it looks better:
```julia
% julia --project=/tmp --startup-file=no -q
julia> @time using GTK3_jll
  0.088641 seconds (271.73 k allocations: 15.071 MiB, 29.69% compilation time)
```
For reference, I got this timing after cleaning up the `.julia/compiled` directory.  I did the same again before rerunning the benchmark for `Preferences.j` `master`:
```julia
% julia --project=/tmp --startup-file=no -q
julia> @time using GTK3_jll
  0.088586 seconds (270.22 k allocations: 14.794 MiB, 29.98% compilation time)
```
Memory allocations got just slightly worse, but the time is pretty much the same

**Comment by timholy** [comment]
I think this is even better. Hold off on merging, though, the `hasmethod` line may change.

**Comment by timholy** [comment]
Now that https://github.com/JuliaLang/julia/pull/43990 has merged without further API changes, we can safely merge this.

**Pull request merged**
